/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: (typeof import('ant-design-vue/es'))['Alert']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACheckbox: (typeof import('ant-design-vue/es'))['Checkbox']
    ACheckboxGroup: (typeof import('ant-design-vue/es'))['CheckboxGroup']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: (typeof import('ant-design-vue/es'))['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ASelect: (typeof import('ant-design-vue/es'))['Select']
    ASelectOption: (typeof import('ant-design-vue/es'))['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATextarea: (typeof import('ant-design-vue/es'))['Textarea']
    FormInput: typeof import('./src/components/form/FormInput.vue')['default']
    HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: (typeof import('./src/components/icons/IconEcosystem.vue'))['default']
    IconSupport: (typeof import('./src/components/icons/IconSupport.vue'))['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ProfileFieldsGroup: (typeof import('./src/components/ProfileFieldsGroup/ProfileFieldsGroup.vue'))['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UserForm: typeof import('./src/components/form/UserForm.vue')['default']
    UsersView: (typeof import('./src/views/UsersView.vue'))['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
